var BaseJoi = require('joi');
var Extension = require('joi-date-extensions');
const Joi = BaseJoi.extend(Extension);

var userSchema = {
    UserID: Joi.number().integer().allow(null).options({convert : false}),
    UserNo: Joi.string().allow("",null).options({convert: false}),
    UserTypeID: Joi.number().integer().allow(null).options({convert : false}).required(),
    UserTitleID: Joi.number().integer().allow(null).options({convert : false}).required(),
    UserFirstName: Joi.string().allow("",null).options({convert: false}).required(),
    UserMiddleName: Joi.string().allow("",null).options({convert: false}),
    UserLastName: Joi.string().allow("",null).options({convert: false}).required(),
    UserFullName: Joi.string().allow("",null).options({convert: false}),
    NickName: Joi.string().allow("",null).options({convert: false}),
    EmailID: Joi.string().allow("",null).options({convert: false}),
    SkypeID: Joi.string().allow("",null).options({convert: false}),
    FacebookID: Joi.string().allow("",null).options({convert: false}),
    WhatsApp: Joi.string().allow("",null).options({convert: false}),
    Viber: Joi.string().allow("",null).options({convert: false}),
    LinkedIN: Joi.string().allow("",null).options({convert: false}),
    ParAddress: Joi.string().allow("",null).options({convert: false}),
    ParThana: Joi.string().allow("",null).options({convert: false}),
    ParPostCode: Joi.string().allow("",null).options({convert: false}),
    ParCountryID: Joi.number().integer().allow(null).options({convert : false}),
    ParStateID: Joi.number().integer().allow(null).options({convert : false}),
    ParCityID: Joi.number().integer().allow(null).options({convert : false}),
    PreAddress: Joi.string().allow("",null).options({convert: false}),
    PreThana: Joi.string().allow("",null).options({convert: false}),
    PrePostCode: Joi.string().allow("",null).options({convert: false}),
    PreCountryID: Joi.number().integer().allow(null).options({convert : false}),
    PreStateID: Joi.number().integer().allow(null).options({convert : false}),
    PreCityID: Joi.number().integer().allow(null).options({convert : false}),
    ReligionID: Joi.number().integer().allow(null).options({convert : false}),
    MobileNo: Joi.string().allow("",null).options({convert: false}),
    PhoneNo: Joi.string().allow("",null).options({convert : false}),
    UniqueIdentity: Joi.string().allow("",null).options({convert: false}),
    BloodGroupID: Joi.number().precision(2).allow(null).options({convert : false}),
    Weigth: Joi.number().precision(2).allow(null).options({convert : false}),
    Height: Joi.number().precision(2).allow(null).options({convert : false}),
    DOB: Joi.string().allow("",null).options({convert: false}),
    BirthCertificate: Joi.string().allow("",null).options({convert: false}),
    PassportNO: Joi.string().allow("",null).options({convert: false}),
    ImageUrl: Joi.string().allow("",null).options({convert: false}),
    SignatureUrl: Joi.string().allow("",null).options({convert: false}),
    FingerUrl: Joi.string().allow("",null).options({convert: false}),
    NID: Joi.string().allow("",null).options({convert: false}),
    OfficeID: Joi.string().allow("",null).options({convert: false}),
    GenderID: Joi.number().integer().allow(null).options({convert : false}),
    Remarks: Joi.string().allow("",null).options({convert: false}),
    IsActive: Joi.number().min(0).max(1).allow(null).options({convert: false}),
    StatusID: Joi.number().integer().allow(null).options({convert : false}),
    InstituteID: Joi.number().integer().allow(null).options({convert : false}),
    CreateBy: Joi.number().integer().allow(null).options({convert : false}),
    CreateOn: Joi.string().allow("",null).options({convert: false}),
    CreatePc: Joi.string().allow("",null).options({convert: false}),
    UpdateBy: Joi.number().integer().allow(null).options({convert : false}),
    UpdateOn: Joi.string().allow("",null).options({convert: false}),
    UpdatePc: Joi.string().allow("",null).options({convert: false}).required(),
    IsDeleted: Joi.number().min(0).max(1).allow(null).options({convert: false}).required(),
    DeleteBy: Joi.number().integer().allow(null).options({convert : false}).required(),
    DeleteOn: Joi.string().allow("",null).options({convert: false}),
    DeletePc: Joi.string().allow("",null).options({convert: false}).required(),
    presentAddressArr:Joi.array(),
    permanentAddressArr:Joi.array(),
    educationInfoArr:Joi.array(),
    guardianInfoArr : Joi.array(),
    jobContractArr : Joi.array(),
    experinceArr : Joi.array() 
}

